---
  Dummy.openstack:
    -
      args:
        sleep: 0.01
      context:
        fuel_environments:
          environments: 5
          release_id: 1
          network_provider: "neutron"
          deployment_mode: "ha_compact"
          net_segment_type: "vlan"
          resource_management_workers: 2
      runner:
        type: "constant"
        times: 4
        concurrency: 2
